<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Persistent "generate-once, reuse-forever" store for adapted content. One row per
     * (chunk, level-signature, cache_version): the shared adapted copy is generated by Gemini
     * exactly once and then reused across all same-level learners — surviving the short-lived
     * file cache, deploys (cache:clear), and the 24h TTL. The signature already encodes a hash
     * of the source chunk, so an instructor edit changes the signature and regenerates.
     */
    public function up(): void
    {
        Schema::create('adaptation_cache', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('chunk_id')->index();
            $table->string('signature', 64);
            $table->string('cache_version', 40);
            $table->string('content_hash', 64);
            $table->longText('adapted_text');
            $table->string('delivery_status', 30)->default('adapted');
            $table->float('similarity_percent')->nullable();
            $table->json('integrity')->nullable();
            $table->uuid('adaptation_id')->nullable();
            $table->timestamps();

            $table->unique(['chunk_id', 'signature', 'cache_version'], 'adapt_cache_unique');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('adaptation_cache');
    }
};
