<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use App\Models\Course;
use App\Models\AiPerformanceSnapshot;
use App\Models\AiSkillMetric;
use App\Models\AiAtRiskStudent;
use App\Models\AiRecommendation;
use App\Models\AiContentRecommendation;
use App\Models\AiGeneratedQuestion;
use App\Models\ActivityPerformance;
use App\Models\DashboardEngagement;

class AIInsightController extends Controller
{
    /**
     * GET /api/v1/courses/{id}/ai/performance
     * Weekly KPI trends — avg grade, completion rate, and engagement score.
     */
    public function performance(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = AiPerformanceSnapshot::where('course_id', $id)
            ->orderBy('recorded_at')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/skills
     * Radar chart data for six skill dimensions.
     */
    public function skills(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $metrics = AiSkillMetric::where('course_id', $id)->get();

        $skillMap = $metrics->pluck('score', 'skill_label')->toArray();

        return response()->json([
            'course_id' => $id,
            'data'      => $skillMap,
        ]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/at-risk
     * GPT-flagged at-risk students with risk level, missed activities, grade, and recommendation.
     */
    public function atRisk(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = AiAtRiskStudent::where('course_id', $id)
            ->orderBy('risk_level', 'desc')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/recommendations
     * Pedagogical recommendations generated by GPT for the course.
     */
    public function recommendations(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = AiRecommendation::where('course_id', $id)
            ->orderBy('generated_at', 'desc')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/content
     * External and internal resource links surfaced by AI based on performance gaps.
     */
    public function contentRecommendations(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = AiContentRecommendation::where('course_id', $id)
            ->orderBy('relevance_score', 'desc')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }

    /**
     * POST /api/v1/courses/{id}/ai/generate-questions
     * Trigger GPT to generate quiz questions for a given topic and difficulty level.
     */
    public function generateQuestions(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'topic'       => 'required|string',
            'difficulty'  => 'required|string|in:easy,medium,hard',
            'count'       => 'sometimes|integer|min:1|max:20',
            'type'        => 'sometimes|string|in:multiple_choice,true_false,short_answer',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        Course::findOrFail($id);

        $generated = AiGeneratedQuestion::create([
            'id'            => Str::uuid()->toString(),
            'course_id'     => $id,
            'topic'         => $request->topic,
            'question_text' => '',
            'question_type' => $request->input('type', 'multiple_choice'),
            'difficulty'    => $request->difficulty,
            'status'        => 'generating',
            'generated_at'  => now(),
        ]);

        return response()->json([
            'message'   => 'Question generation queued.',
            'course_id' => $id,
            'data'      => $generated,
        ]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/generated-questions
     * List all AI-generated questions filtered by status.
     */
    public function generatedQuestions(Request $request, string $id): JsonResponse
    {
        Course::findOrFail($id);

        $query  = AiGeneratedQuestion::where('course_id', $id);
        $status = $request->query('status');

        if ($status) {
            $query->where('status', $status);
        }

        $data = $query->orderBy('generated_at', 'desc')->get();

        return response()->json(['data' => $data, 'course_id' => $id, 'status_filter' => $status]);
    }

    /**
     * PATCH /api/v1/ai/generated-questions/{id}
     * Accept (add_to_bank) or dismiss a GPT-generated question.
     */
    public function updateQuestionStatus(Request $request, string $id): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'status' => 'required|string|in:added_to_bank,dismissed',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $question = AiGeneratedQuestion::findOrFail($id);
        $question->update(['status' => $request->status]);

        return response()->json(['message' => 'Question status updated.', 'data' => $question]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/activity-performance
     * Average score percentage per activity (horizontal bar chart data).
     */
    public function activityPerformance(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = ActivityPerformance::where('course_id', $id)
            ->orderBy('avg_score_percentage', 'desc')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }

    /**
     * GET /api/v1/courses/{id}/ai/engagement
     * Daily active students and submission counts for the engagement area chart.
     */
    public function engagement(string $id): JsonResponse
    {
        Course::findOrFail($id);

        $data = DashboardEngagement::where('course_id', $id)
            ->orderBy('week_of', 'desc')
            ->orderBy('day_label')
            ->get();

        return response()->json(['data' => $data, 'course_id' => $id]);
    }
}
