<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI Insights – EduAI LMS</title>
<style>
  body{margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}
  .wrapper{max-width:600px;margin:40px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)}
  .header{background:linear-gradient(135deg,#0f172a,#1e293b);padding:40px;text-align:center}
  .header h1{color:#fff;margin:0 0 6px;font-size:22px;font-weight:700}
  .header p{color:#94a3b8;margin:0;font-size:14px}
  .body{padding:40px}
  .tier-badge{display:inline-flex;align-items:center;gap:6px;padding:6px 16px;border-radius:999px;font-size:13px;font-weight:600;margin-bottom:20px}
  .profile-chip{display:inline-block;background:#f1f5f9;border:1px solid #e2e8f0;border-radius:8px;padding:8px 16px;font-size:13px;color:#475569;margin-bottom:24px}
  .rec-item{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:18px 20px;margin-bottom:14px}
  .rec-title{font-size:14px;font-weight:700;color:#1e293b;margin:0 0 6px}
  .rec-desc{font-size:13px;color:#64748b;line-height:1.6;margin:0 0 8px}
  .impact{display:inline-block;padding:2px 10px;border-radius:999px;font-size:11px;font-weight:600;text-transform:uppercase}
  .btn{display:inline-block;background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;text-decoration:none;padding:13px 32px;border-radius:10px;font-size:14px;font-weight:600}
  .btn-wrap{text-align:center;margin:28px 0 0}
  .divider{border:none;border-top:1px solid #e2e8f0;margin:32px 0}
  .footer{background:#f8fafc;padding:24px 40px;text-align:center}
  .footer p{margin:0;font-size:12px;color:#94a3b8}
</style>
</head>
<body>

@php
  $tierConfig = [
    'green'    => ['bg'=>'#dcfce7','text'=>'#16a34a','dot'=>'🟢','label'=>'On Track'],
    'amber'    => ['bg'=>'#fef9c3','text'=>'#ca8a04','dot'=>'🟡','label'=>'Needs Attention'],
    'red'      => ['bg'=>'#fee2e2','text'=>'#dc2626','dot'=>'🔴','label'=>'At Risk'],
    'critical' => ['bg'=>'#fce7f3','text'=>'#be185d','dot'=>'🚨','label'=>'Critical'],
  ];
  $tier = $tierConfig[$riskTier] ?? $tierConfig['amber'];

  $impactColors = [
    'high'   => ['bg'=>'#fee2e2','text'=>'#dc2626'],
    'medium' => ['bg'=>'#fef9c3','text'=>'#ca8a04'],
    'low'    => ['bg'=>'#dcfce7','text'=>'#16a34a'],
  ];

  $profileLabels = [
    'H' => 'Humanitarian (H)',
    'A' => 'Analytical (A)',
    'T' => 'Theoretical (T)',
    'C' => 'Creative (C)',
    'mixed' => 'Mixed Profile',
  ];
@endphp

<div class="wrapper">
  <div class="header">
    <h1>🤖 AI Learning Insights</h1>
    <p>Personalised analysis for {{ $courseName }}</p>
  </div>

  <div class="body">
    <p style="font-size:16px;font-weight:600;color:#1e293b;margin:0 0 6px">Hello {{ $userName }},</p>
    <p style="font-size:14px;color:#64748b;line-height:1.7;margin:0 0 20px">
      Your EduAI learning engine has analysed your activity patterns and generated personalised recommendations to help you succeed.
    </p>

    <span class="tier-badge" style="background:{{ $tier['bg'] }};color:{{ $tier['text'] }}">
      {{ $tier['dot'] }} Status: {{ $tier['label'] }}
    </span><br>

    <span class="profile-chip">
      🧠 Learner Profile: <strong>{{ $profileLabels[$profileType] ?? $profileType }}</strong>
    </span>

    <h3 style="font-size:15px;font-weight:700;color:#1e293b;margin:0 0 14px">
      📋 Your Personalised Recommendations
    </h3>

    @forelse($recommendations as $rec)
    @php
      $impact = $impactColors[$rec['impact_level'] ?? 'medium'] ?? $impactColors['medium'];
    @endphp
    <div class="rec-item">
      <p class="rec-title">{{ $rec['title'] ?? '' }}</p>
      <p class="rec-desc">{{ $rec['description'] ?? '' }}</p>
      <span class="impact" style="background:{{ $impact['bg'] }};color:{{ $impact['text'] }}">
        {{ strtoupper($rec['impact_level'] ?? 'medium') }} IMPACT
      </span>
    </div>
    @empty
    <p style="font-size:14px;color:#94a3b8;text-align:center">No recommendations at this time.</p>
    @endforelse

    <div class="btn-wrap">
      <a href="{{ $actionUrl }}" class="btn">View Full AI Insights</a>
    </div>

    <hr class="divider">
    <p style="font-size:13px;color:#94a3b8;line-height:1.6;text-align:center">
      These insights are generated by the EduAI adaptive learning engine based on your engagement patterns in
      <strong>{{ $courseName }}</strong>.
    </p>
  </div>

  <div class="footer">
    <p>© {{ date('Y') }} EduAI LMS · All rights reserved</p>
    <p style="margin-top:4px">Manage notification preferences in your profile settings.</p>
  </div>
</div>
</body>
</html>
